services:
  db:
    image: postgres:16
    container_name: image-gen-db
    environment:
      POSTGRES_DB: image_gen_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres:
